//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Business {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errores {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errores() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Business.Errores", typeof(Errores).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Incorrecto.
        /// </summary>
        internal static string _10001_SROauth_Login_Incorrecto {
            get {
                return ResourceManager.GetString("10001_SROauth_Login_Incorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario Bloqueado.
        /// </summary>
        internal static string _10002_SROauth_Usuario_Bloqueado {
            get {
                return ResourceManager.GetString("10002_SROauth_Usuario_Bloqueado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SROauth.
        /// </summary>
        internal static string _10003_SROauth_Error_Generio {
            get {
                return ResourceManager.GetString("10003_SROauth_Error_Generio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetInfoUserAsync .
        /// </summary>
        internal static string _10004_SROauth_Info_User {
            get {
                return ResourceManager.GetString("10004_SROauth_Info_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrearClaisUsuario.
        /// </summary>
        internal static string _10005_SROauth_Clais {
            get {
                return ResourceManager.GetString("10005_SROauth_Clais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateToken.
        /// </summary>
        internal static string _10006_SROauth_GeneraToken {
            get {
                return ResourceManager.GetString("10006_SROauth_GeneraToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GenerateRefreshToken.
        /// </summary>
        internal static string _10007_SROauth_GenerateRefreshToken {
            get {
                return ResourceManager.GetString("10007_SROauth_GenerateRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveTokenRefres.
        /// </summary>
        internal static string _10008_SROauth_SaveToken {
            get {
                return ResourceManager.GetString("10008_SROauth_SaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RefresAsync.
        /// </summary>
        internal static string _10009_SROauth_RefresToken {
            get {
                return ResourceManager.GetString("10009_SROauth_RefresToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token de actualización no válido.
        /// </summary>
        internal static string _10010_SROauth_Refresh_Token_Invalido {
            get {
                return ResourceManager.GetString("10010_SROauth_Refresh_Token_Invalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Invalido.
        /// </summary>
        internal static string _10011_SROauth_Token_Valido {
            get {
                return ResourceManager.GetString("10011_SROauth_Token_Valido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetPrincipalFromExpiredToken.
        /// </summary>
        internal static string _10012_SROauth_GetPrincipalFromExpiredToken {
            get {
                return ResourceManager.GetString("10012_SROauth_GetPrincipalFromExpiredToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsBloquedUser.
        /// </summary>
        internal static string _10013_SROauth_IsBloquedUser {
            get {
                return ResourceManager.GetString("10013_SROauth_IsBloquedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRefreshToken.
        /// </summary>
        internal static string _10014_SROauth_GetRefreshToken {
            get {
                return ResourceManager.GetString("10014_SROauth_GetRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResetPassword.
        /// </summary>
        internal static string _10015_SROauth_ResetPassword {
            get {
                return ResourceManager.GetString("10015_SROauth_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModifyAccessData.
        /// </summary>
        internal static string _10016_SROauth_ModifyAccessData {
            get {
                return ResourceManager.GetString("10016_SROauth_ModifyAccessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuario no encontrado.
        /// </summary>
        internal static string _10017_SROauth_Usuario_NotFound {
            get {
                return ResourceManager.GetString("10017_SROauth_Usuario_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en servicio SRVisita metodo Get.
        /// </summary>
        internal static string _10018_SRVisitas_Get {
            get {
                return ResourceManager.GetString("10018_SRVisitas_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el mapeo de los filtros del metodo get.
        /// </summary>
        internal static string _10019_SRVisitas_Mapper_Get {
            get {
                return ResourceManager.GetString("10019_SRVisitas_Mapper_Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el mapeo de los datos devuelvos de la consulta.
        /// </summary>
        internal static string _10020_SRVisitas_Mapper_Get_Retorno {
            get {
                return ResourceManager.GetString("10020_SRVisitas_Mapper_Get_Retorno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddLogTransaction.
        /// </summary>
        internal static string _10021_SRBase_AddLogTransaction {
            get {
                return ResourceManager.GetString("10021_SRBase_AddLogTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InitOperation.
        /// </summary>
        internal static string _10022_SRBase_InitOperation {
            get {
                return ResourceManager.GetString("10022_SRBase_InitOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCadena.
        /// </summary>
        internal static string _10023_SRMaster_GetCadena {
            get {
                return ResourceManager.GetString("10023_SRMaster_GetCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error generico Master.
        /// </summary>
        internal static string _10024_SRMaster_Generico {
            get {
                return ResourceManager.GetString("10024_SRMaster_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena no esta informada.
        /// </summary>
        internal static string _10025_SRMaster_CadenaVacia {
            get {
                return ResourceManager.GetString("10025_SRMaster_CadenaVacia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCanales.
        /// </summary>
        internal static string _10025_SRMaster_Canales {
            get {
                return ResourceManager.GetString("10025_SRMaster_Canales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de familia no esta informada.
        /// </summary>
        internal static string _10026_SRMaster_Categorias_CdFamilia {
            get {
                return ResourceManager.GetString("10026_SRMaster_Categorias_CdFamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de sector no esta informado.
        /// </summary>
        internal static string _10027_SRMaster_Categorias_CdSector {
            get {
                return ResourceManager.GetString("10027_SRMaster_Categorias_CdSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCategorias.
        /// </summary>
        internal static string _10028_SRMaster_Categorias {
            get {
                return ResourceManager.GetString("10028_SRMaster_Categorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de Ensena no esta informado.
        /// </summary>
        internal static string _10029_SRMaster_Cluster_CdEnsena {
            get {
                return ResourceManager.GetString("10029_SRMaster_Cluster_CdEnsena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena no esta informada.
        /// </summary>
        internal static string _10030_SRMaster_Cluster_CdCadena {
            get {
                return ResourceManager.GetString("10030_SRMaster_Cluster_CdCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCluster.
        /// </summary>
        internal static string _10031_SRMaster_Cluster {
            get {
                return ResourceManager.GetString("10031_SRMaster_Cluster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnsena.
        /// </summary>
        internal static string _10032_SRMaster_Ensena {
            get {
                return ResourceManager.GetString("10032_SRMaster_Ensena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena no esta informada.
        /// </summary>
        internal static string _10033_SRMaster_Ensena_CdCandena {
            get {
                return ResourceManager.GetString("10033_SRMaster_Ensena_CdCandena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetEnsenaMultiple.
        /// </summary>
        internal static string _10034_SRMaster_EnsenaMultiple {
            get {
                return ResourceManager.GetString("10034_SRMaster_EnsenaMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La cadena no esta informada.
        /// </summary>
        internal static string _10035_SRMaster_EnsenaMultiple_CdCadena {
            get {
                return ResourceManager.GetString("10035_SRMaster_EnsenaMultiple_CdCadena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetFamilia.
        /// </summary>
        internal static string _10036_SRMaster_Familia {
            get {
                return ResourceManager.GetString("10036_SRMaster_Familia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El sector no esta informado.
        /// </summary>
        internal static string _10037_SRMaster_Familia_CdSector {
            get {
                return ResourceManager.GetString("10037_SRMaster_Familia_CdSector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetMunicipio.
        /// </summary>
        internal static string _10038_SRMaster_Municipio {
            get {
                return ResourceManager.GetString("10038_SRMaster_Municipio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La provincia es obligatoria.
        /// </summary>
        internal static string _10039_SRMaster_Municipio_CdProvincia {
            get {
                return ResourceManager.GetString("10039_SRMaster_Municipio_CdProvincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetProvincia.
        /// </summary>
        internal static string _10040_SRMaster_Provincia {
            get {
                return ResourceManager.GetString("10040_SRMaster_Provincia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSector.
        /// </summary>
        internal static string _10041_SRMaster_Sector {
            get {
                return ResourceManager.GetString("10041_SRMaster_Sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetClientes.
        /// </summary>
        internal static string _10042_SRMaster_Clientes {
            get {
                return ResourceManager.GetString("10042_SRMaster_Clientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetVendedores.
        /// </summary>
        internal static string _10043_SRMaster_Vendedores {
            get {
                return ResourceManager.GetString("10043_SRMaster_Vendedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El cliente es obligatorio.
        /// </summary>
        internal static string _10044_SRMaster_Vendedores_IdCliente {
            get {
                return ResourceManager.GetString("10044_SRMaster_Vendedores_IdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTiendas.
        /// </summary>
        internal static string _10045_SRMaster_Tiendas {
            get {
                return ResourceManager.GetString("10045_SRMaster_Tiendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo del cliente es obligatorio.
        /// </summary>
        internal static string _10046_SRMaster_Tiendas_CdCliente {
            get {
                return ResourceManager.GetString("10046_SRMaster_Tiendas_CdCliente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo del vendedor es obligatorio.
        /// </summary>
        internal static string _10047_SRMaster_Tiendas_CdVendedor {
            get {
                return ResourceManager.GetString("10047_SRMaster_Tiendas_CdVendedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSegmentos.
        /// </summary>
        internal static string _10048_SRMaster_Segmentos {
            get {
                return ResourceManager.GetString("10048_SRMaster_Segmentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de sector es obligatorio.
        /// </summary>
        internal static string _10049_SRMaster_Segmentos_cdsector {
            get {
                return ResourceManager.GetString("10049_SRMaster_Segmentos_cdsector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de familia es obligatorio.
        /// </summary>
        internal static string _10050_SRMaster_Segmentos_cdfamilia {
            get {
                return ResourceManager.GetString("10050_SRMaster_Segmentos_cdfamilia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El codigo de la categoria es obligatorio.
        /// </summary>
        internal static string _10051_SRMaster_Segmentos_cdcategorias {
            get {
                return ResourceManager.GetString("10051_SRMaster_Segmentos_cdcategorias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AsignarConfiguracionTienda.
        /// </summary>
        internal static string _10052_SRCluster_AsignarConfiguracionTienda {
            get {
                return ResourceManager.GetString("10052_SRCluster_AsignarConfiguracionTienda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRCluster.
        /// </summary>
        internal static string _10053_SRCluster_Generico {
            get {
                return ResourceManager.GetString("10053_SRCluster_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRCuestionario.
        /// </summary>
        internal static string _10054_SRCuestionario_Generico {
            get {
                return ResourceManager.GetString("10054_SRCuestionario_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BorrarCuestionario.
        /// </summary>
        internal static string _10055_SRCuestionario_BorrarCuestionario {
            get {
                return ResourceManager.GetString("10055_SRCuestionario_BorrarCuestionario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetCuestionario.
        /// </summary>
        internal static string _10056_SRCuestionario_GetCuestionarios {
            get {
                return ResourceManager.GetString("10056_SRCuestionario_GetCuestionarios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRRutas.
        /// </summary>
        internal static string _10057_SRRutas_Generico {
            get {
                return ResourceManager.GetString("10057_SRRutas_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetRutas.
        /// </summary>
        internal static string _10058_SRRutas_GetRutas {
            get {
                return ResourceManager.GetString("10058_SRRutas_GetRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicarRutas.
        /// </summary>
        internal static string _10059_SRRutas_DuplicarRutas {
            get {
                return ResourceManager.GetString("10059_SRRutas_DuplicarRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModificarRutas.
        /// </summary>
        internal static string _10060_SRRutas_ModificarRutas {
            get {
                return ResourceManager.GetString("10060_SRRutas_ModificarRutas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SRSurtido.
        /// </summary>
        internal static string _10061_SRSurtido_Generico {
            get {
                return ResourceManager.GetString("10061_SRSurtido_Generico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetSurtido.
        /// </summary>
        internal static string _10062_SRSurtido_GetSurtido {
            get {
                return ResourceManager.GetString("10062_SRSurtido_GetSurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DuplicarSurtidos.
        /// </summary>
        internal static string _10063_SRSurtido_DuplicarSurtidos {
            get {
                return ResourceManager.GetString("10063_SRSurtido_DuplicarSurtidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BajaSurtido.
        /// </summary>
        internal static string _10064_SRSurtido_BajaSurtido {
            get {
                return ResourceManager.GetString("10064_SRSurtido_BajaSurtido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surtido Maximo no encontrado.
        /// </summary>
        internal static string _10065_SRSurtido_Longitud_Fichero {
            get {
                return ResourceManager.GetString("10065_SRSurtido_Longitud_Fichero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SurtidoMaxivo.
        /// </summary>
        internal static string _10066_SRSurtido_SurtidoMaxivo {
            get {
                return ResourceManager.GetString("10066_SRSurtido_SurtidoMaxivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en servicio SRVisita metodo GetVisitasRespuesta.
        /// </summary>
        internal static string _10067_SRVisita_GetVisitasRespuesta {
            get {
                return ResourceManager.GetString("10067_SRVisita_GetVisitasRespuesta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetTipoPregutasRespuestas.
        /// </summary>
        internal static string _10068_SRMaster_TiposRespuestas {
            get {
                return ResourceManager.GetString("10068_SRMaster_TiposRespuestas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetVisitaRespuesta.
        /// </summary>
        internal static string _10068_SRVisita_SetVisitaRespuesta {
            get {
                return ResourceManager.GetString("10068_SRVisita_SetVisitaRespuesta", resourceCulture);
            }
        }
    }
}
